WR_CONF = [
    "EMS PExtra",
    "EMS UG",
    "EMS OG",
    "EMS Timer",
    "PSoll",
    "U Verbund L1",
    "U Verbund L2",
    "U Verbund L3",
    "I Verbund L1",
    "I Verbund L2",
    "I Verbund L3",
    "U Insel L1",
    "U Insel L2",
    "U Insel L3",
    "I Insel L1",
    "I Insel L2",
    "I Insel L3",
    "Temp L1",
    "Temp L2",
    "Temp L3",
    "TBoard",
    "FNetz",
    "U N->PE",
    "OnlineStatus",
    "System State",
    "SK",
    "RB_IP",
    "RCMU",
    "UVcc",
    "UZwk",
    "UMp",
    "Luefter",
    "WR Ctrl",
    "ENS Ctrl",
    "EMS Ctrl",
    "EMS Mode",
    "POpt",
    "BetrFlags1",
    "BetrFlags2",
    "PMB",
    "EMB",
    "General State"
]

ENS_CONF = [
    "FNetz",
    "U_V_L1",
    "U_V_L2",
    "U_V_L3"
]

EMETER_CONF = [
    "FNetz",
    "SensState",
    "U_V_L1",
    "U_V_L2",
    "U_V_L3",
    "Iw_V_L1",
    "Iw_V_L2",
    "Iw_V_L3",
    "Ib_V_L1",
    "Ib_V_L2",
    "Ib_V_L3",
    "Is_V_L1",
    "Is_V_L2",
    "Is_V_L3",
    "Iw_PV_L1",
    "Iw_PV_L2",
    "Iw_PV_L3",
    "Ib_PV_L1",
    "Ib_PV_L2",
    "Ib_PV_L3",
    "Is_PV_L1",
    "Is_PV_L2",
    "Is_PV_L3"
]

CHARGER_CONF = [
    "Index",
    "Enabled",
    "SOC_GS",
    "State",
    "U",
    "I",
    "UOut",
    "UCool",
    "UVcc",
    "THT",
    "TTr",
    "TBoard",
    "PSoll",
    "SOHCmax",
    "SOHCuxtime",
    "SOHDmax",
    "SOHDuxtime",
    "ErrorFlags",
    "HelperFlags",
    "BetrFlags",
    "SteuerFlags",
    "BattState",
    "SVDFflags",
    "RSOCmin",
    "RSOCmax",
    "SOCcut",
    "DSOC_Thr1",
    "DSOC_Thr2",
    "SVDFtime",
    "SVDFcnt1s",
    "BattData"
]

BATT_CONF = [
    "LG_Neo",
    "Type",
    "Alarms_Rack",
    "Warnings_Rack",
    "U_Rack",
    "I_Rack",
    "SOC_Rack",
    "SOH_Rack",
    "UMax_Rack",
    "IChrgLimit_Rack",
    "IDiscLimit_Rack",
    "Temp_Rack",
    "ModulData"
]

MODULE_CONF = [
    "Status",
    "Alarms_Modul",
    "Warnings_Modul",
    "Faults1_Modul",
    "Faults2_Modul",
    "IntErrors_Modul",
    "SOC_Modul",
    "SOH_Modul",
    "U_Modul",
    "I_Modul",
    "UMin_Modul",
    "UMax_Modul",
    "UAvg_Modul",
    "IChrgLimitBatt",
    "IDiscLimitBatt",
    "PChrgLimitBatt",
    "PDiscLimitBatt",
    "Temp1",
    "Temp2",
    "TempAvg",
    "BalTarg",
    "AnzCycles",
    "CapDesign",
    "CapUsable",
    "CapRemain",
    "SVDStat",
    "PackSerNr",
    "LifeEnergy",
    "RackSOCmax",
    "RackSOCmin",
    "SwVersFull",
    "CellVolt1",
    "CellVolt2",
    "CellVolt3",
    "CellVolt4",
    "CellVolt5",
    "CellVolt6",
    "CellVolt7",
    "CellVolt8",
    "CellVolt9",
    "CellVolt10",
    "CellVolt11",
    "CellVolt12",
    "CellVolt13",
    "CellVolt14"
]

